name: 🎭 Playwright Tests with CTRF & AI Reporting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser to test with'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - chromium
          - firefox
          - webkit
      environment:
        description: 'Test environment'
        required: false
        default: 'staging'
        type: choice
        options:
          - staging
          - production
          - development
      run_ai_analysis:
        description: 'AI analysis runs by default (this option is informational)'
        required: false
        default: true
        type: boolean

env:
  NODE_VERSION: '20'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 📋 Display Manual Run Configuration
      if: github.event_name == 'workflow_dispatch'
      run: |
        echo "🎯 Manual Test Run Configuration:"
        echo "Browser: ${{ github.event.inputs.browser || 'all' }}"
        echo "Environment: ${{ github.event.inputs.environment || 'staging' }}"
        echo "AI Analysis: Always enabled"
        echo "Triggered by: ${{ github.actor }}"
        echo "=================================="
      
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: npm ci
      
    - name: 🎭 Install Playwright Browsers
      run: npx playwright install --with-deps
      
    - name: 📊 Install CTRF CLI tool
      run: npm install -g ctrf
      
    - name: 🤖 Install Ollama (for AI analysis)
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        # Start Ollama service in background
        ollama serve &
        # Wait for service to start
        sleep 10
        # Pull a lightweight model for testing
        ollama pull llama3.2:1b
      continue-on-error: true
      
    - name: 🧪 Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.browser }}" = "all" ] || [ "${{ github.event.inputs.browser }}" = "" ]; then
          echo "Running tests on all browsers..."
          npx playwright test
        else
          echo "Running tests on ${{ github.event.inputs.browser }} browser..."
          npx playwright test --project=${{ github.event.inputs.browser }}
        fi
      continue-on-error: true
      env:
        TEST_ENV: ${{ github.event.inputs.environment || 'staging' }}
      
    - name: 📊 Generate CTRF Summary
      if: always()
      run: |
        if [ -f "ctrf/ctrf-report.json" ]; then
          npm run ctrf:summary
        else
          echo "No CTRF report found"
        fi
      continue-on-error: true
      
    - name: 🤖 Generate AI Analysis (always runs)
      if: always()
      run: |
        if [ -f "ctrf/ctrf-report.json" ]; then
          echo "Generating AI analysis..."
          npm run ai:report
        else
          echo "No CTRF report for AI analysis"
        fi
      continue-on-error: true
      
    - name: 📋 Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.event.inputs.browser || 'all' }}-${{ github.event.inputs.environment || 'auto' }}
        path: playwright-report/
        retention-days: 30
        
    - name: 📊 Upload CTRF Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ctrf-report-${{ github.event.inputs.browser || 'all' }}-${{ github.event.inputs.environment || 'auto' }}
        path: ctrf/
        retention-days: 30
        
    - name: 🤖 Upload AI Analysis Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ai-analysis-report-${{ github.event.inputs.browser || 'all' }}-${{ github.event.inputs.environment || 'auto' }}
        path: |
          ai-reports/
          *.html
        retention-days: 30
